import { DecompositionResult, UserStory, Epic } from '../types/agile';

/**
 * Format a single user story as clean, ticket-ready Markdown for Jira, Linear, or GitHub Issues.
 */
export function formatStoryMarkdown(story: UserStory, epic?: Epic): string {
  const epicLine = epic ? `**Epic:** ${epic.id} — ${epic.title}\n` : '';
  const deps = story.dependsOn.length > 0 ? story.dependsOn.join(', ') : 'None';
  const blocks = story.blocks.length > 0 ? story.blocks.join(', ') : 'None';

  const gherkinList = story.acceptanceCriteria
    .map((ac) => `- [ ] ${ac}`)
    .join('\n');

  const risksList = story.technicalRisks.length > 0
    ? story.technicalRisks.map((r) => `- ⚠️ ${r}`).join('\n')
    : '- No critical technical risks identified';

  return `### [${story.id}] ${story.title}
${epicLine}**Estimate / Size:** ${story.complexity}
**Dependencies:** ${deps} | **Blocks:** ${blocks}

#### User Story
- **As a:** ${story.asA}
- **I want:** ${story.iWant}
- **So that:** ${story.soThat}

#### Acceptance Criteria (Gherkin)
${gherkinList}

#### Technical Considerations & Risks
${risksList}
`;
}

/**
 * Format the entire sprint decomposition as a comprehensive Agile backlog markdown document.
 */
export function formatSprintBacklogMarkdown(result: DecompositionResult): string {
  const epicMap = new Map<string, Epic>();
  result.epics.forEach((e) => epicMap.set(e.id, e));

  const epicsSection = result.epics
    .map((e) => `### ${e.id}: ${e.title}\n${e.objective}\n`)
    .join('\n');

  const storiesSection = result.userStories
    .map((s) => formatStoryMarkdown(s, epicMap.get(s.epicId)))
    .join('\n---\n\n');

  return `# Sprint Backlog: Feature Clarification

## Executive Summary
${result.summary}

## Milestone Epics
${epicsSection}

## User Stories & Acceptance Criteria
${storiesSection}

## Execution Dependency Diagram
\`\`\`mermaid
${result.mermaidDiagram}
\`\`\`

---
*Generated by SprintClarify with Google Gen AI SDK (\`responseSchema\`)*
`;
}

/**
 * Helper to copy string to clipboard with fallback.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (navigator?.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fallback below
    }
  }

  // Fallback for environments where navigator.clipboard might be restricted
  try {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    console.error('Clipboard copy failed:', err);
    return false;
  }
}
